# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/michel/progrk/eric/biblioapp/main_window_biblio.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindowBiblio(object):
    def setupUi(self, mainWindowBiblio):
        mainWindowBiblio.setObjectName("mainWindowBiblio")
        mainWindowBiblio.resize(905, 1000)
        self.centralWidget = QtWidgets.QWidget(mainWindowBiblio)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeViewLivres = QtWidgets.QTreeView(self.centralWidget)
        self.treeViewLivres.setObjectName("treeViewLivres")
        self.verticalLayout.addWidget(self.treeViewLivres)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxGenre = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.comboBoxGenre.addItem("")
        self.comboBoxGenre.addItem("")
        self.comboBoxGenre.addItem("")
        self.comboBoxGenre.addItem("")
        self.comboBoxGenre.addItem("")
        self.comboBoxGenre.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxGenre)
        spacerItem = QtWidgets.QSpacerItem(40, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEditParution = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditParution.setObjectName("dateEditParution")
        self.horizontalLayout_2.addWidget(self.dateEditParution)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEditAuteur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAuteur.setObjectName("lineEditAuteur")
        self.gridLayout.addWidget(self.lineEditAuteur, 1, 1, 1, 1)
        self.lineEditTitre = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTitre.setObjectName("lineEditTitre")
        self.gridLayout.addWidget(self.lineEditTitre, 0, 1, 1, 1)
        self.lineEditEditeur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEditeur.setObjectName("lineEditEditeur")
        self.gridLayout.addWidget(self.lineEditEditeur, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doubleSpinBoxPrix = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxPrix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxPrix.setPrefix("")
        self.doubleSpinBoxPrix.setMaximum(9999.99)
        self.doubleSpinBoxPrix.setObjectName("doubleSpinBoxPrix")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxPrix)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 1, 1, 1)
        self.textEditResume = QtWidgets.QTextEdit(self.groupBox)
        self.textEditResume.setObjectName("textEditResume")
        self.gridLayout.addWidget(self.textEditResume, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButtonNouveau = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.horizontalLayout_4.addWidget(self.pushButtonNouveau)
        spacerItem4 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButtonSauvegarder = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSauvegarder.setObjectName("pushButtonSauvegarder")
        self.horizontalLayout_4.addWidget(self.pushButtonSauvegarder)
        spacerItem5 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout_4.addWidget(self.pushButtonSupprimer)
        spacerItem6 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        mainWindowBiblio.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindowBiblio)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFuchier = QtWidgets.QMenu(self.menuBar)
        self.menuFuchier.setObjectName("menuFuchier")
        mainWindowBiblio.setMenuBar(self.menuBar)
        self.actionOuvrir = QtWidgets.QAction(mainWindowBiblio)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionEnregistrer = QtWidgets.QAction(mainWindowBiblio)
        self.actionEnregistrer.setObjectName("actionEnregistrer")
        self.actionQuitter = QtWidgets.QAction(mainWindowBiblio)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFuchier.addAction(self.actionOuvrir)
        self.menuFuchier.addAction(self.actionEnregistrer)
        self.menuFuchier.addSeparator()
        self.menuFuchier.addAction(self.actionQuitter)
        self.menuBar.addAction(self.menuFuchier.menuAction())

        self.retranslateUi(mainWindowBiblio)
        QtCore.QMetaObject.connectSlotsByName(mainWindowBiblio)

    def retranslateUi(self, mainWindowBiblio):
        _translate = QtCore.QCoreApplication.translate
        mainWindowBiblio.setWindowTitle(_translate("mainWindowBiblio", "BiblioApp"))
        self.groupBox.setTitle(_translate("mainWindowBiblio", "Detail"))
        self.label_7.setText(_translate("mainWindowBiblio", "Prix:"))
        self.label_3.setText(_translate("mainWindowBiblio", "Genre:"))
        self.label_5.setText(_translate("mainWindowBiblio", "Annee de parution :"))
        self.comboBoxGenre.setItemText(0, _translate("mainWindowBiblio", "---"))
        self.comboBoxGenre.setItemText(1, _translate("mainWindowBiblio", "Biographie"))
        self.comboBoxGenre.setItemText(2, _translate("mainWindowBiblio", "Fantastique"))
        self.comboBoxGenre.setItemText(3, _translate("mainWindowBiblio", "Histoire"))
        self.comboBoxGenre.setItemText(4, _translate("mainWindowBiblio", "Policier"))
        self.comboBoxGenre.setItemText(5, _translate("mainWindowBiblio", "Science-Fiction"))
        self.label_2.setText(_translate("mainWindowBiblio", "Auteur(s) : "))
        self.dateEditParution.setDisplayFormat(_translate("mainWindowBiblio", "yyyy"))
        self.label.setText(_translate("mainWindowBiblio", "Titre :"))
        self.label_6.setText(_translate("mainWindowBiblio", "                Resume"))
        self.label_4.setText(_translate("mainWindowBiblio", "Editeur :"))
        self.doubleSpinBoxPrix.setSuffix(_translate("mainWindowBiblio", "euro"))
        self.pushButtonNouveau.setText(_translate("mainWindowBiblio", "Nouveau"))
        self.pushButtonSauvegarder.setText(_translate("mainWindowBiblio", "Sauvegarder"))
        self.pushButtonSupprimer.setText(_translate("mainWindowBiblio", "Supprimer"))
        self.menuFuchier.setTitle(_translate("mainWindowBiblio", "Fichier"))
        self.actionOuvrir.setText(_translate("mainWindowBiblio", "Ouvrir"))
        self.actionOuvrir.setShortcut(_translate("mainWindowBiblio", "Ctrl+O"))
        self.actionEnregistrer.setText(_translate("mainWindowBiblio", "Enregistrer"))
        self.actionEnregistrer.setShortcut(_translate("mainWindowBiblio", "Ctrl+S"))
        self.actionQuitter.setText(_translate("mainWindowBiblio", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindowBiblio = QtWidgets.QMainWindow()
    ui = Ui_mainWindowBiblio()
    ui.setupUi(mainWindowBiblio)
    mainWindowBiblio.show()
    sys.exit(app.exec_())

