# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.text = QtWidgets.QTextEdit(self.centralWidget)
        self.text.setGeometry(QtCore.QRect(13, 19, 581, 431))
        self.text.setObjectName("text")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/png/022-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icones/png/003-save-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionColor = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icones/png/024-pantone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon2)
        self.actionColor.setObjectName("actionColor")
        self.actioncancel = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icones/png/025-x-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncancel.setIcon(icon3)
        self.actioncancel.setObjectName("actioncancel")
        self.actionback = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icones/png/027-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionback.setIcon(icon4)
        self.actionback.setObjectName("actionback")
        self.actionnext = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icones/png/026-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnext.setIcon(icon5)
        self.actionnext.setObjectName("actionnext")
        self.actionmise_page = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icones/png/019-text-font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmise_page.setIcon(icon6)
        self.actionmise_page.setObjectName("actionmise_page")
        self.actionfonce = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icones/png/016-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfonce.setIcon(icon7)
        self.actionfonce.setObjectName("actionfonce")
        self.actionsouligner = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icones/png/020-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsouligner.setIcon(icon8)
        self.actionsouligner.setObjectName("actionsouligner")
        self.actionitalique = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icones/png/012-italic-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionitalique.setIcon(icon9)
        self.actionitalique.setObjectName("actionitalique")
        self.actionaligner_debut = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icones/png/009-left-alignment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaligner_debut.setIcon(icon10)
        self.actionaligner_debut.setObjectName("actionaligner_debut")
        self.actionaligner_fin = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icones/png/004-right-alignment-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaligner_fin.setIcon(icon11)
        self.actionaligner_fin.setObjectName("actionaligner_fin")
        self.actionaligner_centrer = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icones/png/010-center-alignment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaligner_centrer.setIcon(icon12)
        self.actionaligner_centrer.setObjectName("actionaligner_centrer")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icones/png/013-delete-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondelete.setIcon(icon13)
        self.actiondelete.setObjectName("actiondelete")
        self.actiondossier = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icones/png/002-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondossier.setIcon(icon14)
        self.actiondossier.setObjectName("actiondossier")
        self.mainToolBar.addAction(self.actionNewFile)
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addAction(self.actiondossier)
        self.mainToolBar.addAction(self.actioncancel)
        self.mainToolBar.addAction(self.actionColor)
        self.mainToolBar.addAction(self.actionback)
        self.mainToolBar.addAction(self.actionnext)
        self.mainToolBar.addAction(self.actionmise_page)
        self.mainToolBar.addAction(self.actionfonce)
        self.mainToolBar.addAction(self.actionsouligner)
        self.mainToolBar.addAction(self.actionitalique)
        self.mainToolBar.addAction(self.actionaligner_debut)
        self.mainToolBar.addAction(self.actionaligner_centrer)
        self.mainToolBar.addAction(self.actionaligner_fin)
        self.mainToolBar.addAction(self.actiondelete)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.actionNewFile.setText(_translate("MainWindow", "NewFile"))
        self.actionNewFile.setToolTip(_translate("MainWindow", "Nouveau fichier"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Enregistrer"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionColor.setToolTip(_translate("MainWindow", "Modifier la couleur"))
        self.actioncancel.setText(_translate("MainWindow", "cancel"))
        self.actioncancel.setToolTip(_translate("MainWindow", "Supprimer"))
        self.actionback.setText(_translate("MainWindow", "back"))
        self.actionback.setToolTip(_translate("MainWindow", "Derrière"))
        self.actionback.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionnext.setText(_translate("MainWindow", "next"))
        self.actionnext.setToolTip(_translate("MainWindow", "Aller devant"))
        self.actionnext.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionmise_page.setText(_translate("MainWindow", "mise_page"))
        self.actionmise_page.setToolTip(_translate("MainWindow", "Mise en page"))
        self.actionfonce.setText(_translate("MainWindow", "fonce"))
        self.actionfonce.setToolTip(_translate("MainWindow", "Couleur foncée"))
        self.actionfonce.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionsouligner.setText(_translate("MainWindow", "souligner"))
        self.actionsouligner.setToolTip(_translate("MainWindow", "Souligner le texte"))
        self.actionsouligner.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionitalique.setText(_translate("MainWindow", "italique"))
        self.actionitalique.setToolTip(_translate("MainWindow", "Mettre en italique"))
        self.actionitalique.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionaligner_debut.setText(_translate("MainWindow", "aligner_debut"))
        self.actionaligner_debut.setToolTip(_translate("MainWindow", "Alignement à partir de la gauche"))
        self.actionaligner_fin.setText(_translate("MainWindow", "aligner_fin"))
        self.actionaligner_fin.setToolTip(_translate("MainWindow", "Alignement à partir de la droite"))
        self.actionaligner_centrer.setText(_translate("MainWindow", "aligner_centrer"))
        self.actionaligner_centrer.setToolTip(_translate("MainWindow", "Alignement à partir du centre"))
        self.actiondelete.setText(_translate("MainWindow", "delete"))
        self.actiondelete.setToolTip(_translate("MainWindow", "Supprimer"))
        self.actiondelete.setShortcut(_translate("MainWindow", "Shift+Del"))
        self.actiondossier.setText(_translate("MainWindow", "dossier"))
        self.actiondossier.setToolTip(_translate("MainWindow", "Ouvrir un dossier"))
        self.actiondossier.setShortcut(_translate("MainWindow", "Ctrl+O"))

