# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/michel/progrk/eric/BiblioApp2/main_window_biblioApp.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window_biblioApp(object):
    def setupUi(self, main_window_biblioApp):
        main_window_biblioApp.setObjectName("main_window_biblioApp")
        main_window_biblioApp.resize(800, 900)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        main_window_biblioApp.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/png/001-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window_biblioApp.setWindowIcon(icon)
        main_window_biblioApp.setStyleSheet("#centralwidget, #groupBox, #centralwidget{\n"
" background-color:qlineargradient(spread:pad, x1:0.936, y1:0.188, x2:0.091, y2:1, stop:0 rgba(191, 249, 92, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"\n"
"")
        self.centralWidget = QtWidgets.QWidget(main_window_biblioApp)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeViewLivres = QtWidgets.QTreeView(self.centralWidget)
        self.treeViewLivres.setObjectName("treeViewLivres")
        self.gridLayout_2.addWidget(self.treeViewLivres, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditTitre = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTitre.setObjectName("lineEditTitre")
        self.gridLayout.addWidget(self.lineEditTitre, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditAuteur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAuteur.setObjectName("lineEditAuteur")
        self.gridLayout.addWidget(self.lineEditAuteur, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBoxGenre = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.horizontalLayout_4.addWidget(self.comboBoxGenre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditEditeur = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditEditeur.setObjectName("lineEditEditeur")
        self.gridLayout.addWidget(self.lineEditEditeur, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateEditAnnee = QtWidgets.QDateEdit(self.groupBox)
        self.dateEditAnnee.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateEditAnnee.setObjectName("dateEditAnnee")
        self.horizontalLayout_3.addWidget(self.dateEditAnnee)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.plainTextEditResume = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEditResume.setObjectName("plainTextEditResume")
        self.gridLayout.addWidget(self.plainTextEditResume, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doubleSpinBoxPrix = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxPrix.setMaximum(9999.99)
        self.doubleSpinBoxPrix.setObjectName("doubleSpinBoxPrix")
        self.horizontalLayout_2.addWidget(self.doubleSpinBoxPrix)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButtonNouveau = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonNouveau.setObjectName("pushButtonNouveau")
        self.horizontalLayout.addWidget(self.pushButtonNouveau)
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButtonSauvegarder = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSauvegarder.setObjectName("pushButtonSauvegarder")
        self.horizontalLayout.addWidget(self.pushButtonSauvegarder)
        spacerItem5 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButtonSupprimer = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSupprimer.setObjectName("pushButtonSupprimer")
        self.horizontalLayout.addWidget(self.pushButtonSupprimer)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        main_window_biblioApp.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(main_window_biblioApp)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFichier = QtWidgets.QMenu(self.menuBar)
        self.menuFichier.setObjectName("menuFichier")
        main_window_biblioApp.setMenuBar(self.menuBar)
        self.actionQuitter = QtWidgets.QAction(main_window_biblioApp)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionQuitter)
        self.menuFichier.addSeparator()
        self.menuBar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(main_window_biblioApp)
        QtCore.QMetaObject.connectSlotsByName(main_window_biblioApp)

    def retranslateUi(self, main_window_biblioApp):
        _translate = QtCore.QCoreApplication.translate
        main_window_biblioApp.setWindowTitle(_translate("main_window_biblioApp", "MainWindow"))
        self.groupBox.setTitle(_translate("main_window_biblioApp", "Detail"))
        self.label.setText(_translate("main_window_biblioApp", "                     Titre"))
        self.label_2.setText(_translate("main_window_biblioApp", "                   Auteur"))
        self.label_3.setText(_translate("main_window_biblioApp", "                   Genre"))
        self.label_4.setText(_translate("main_window_biblioApp", "                  Editeur"))
        self.label_5.setText(_translate("main_window_biblioApp", "Annee de parution"))
        self.dateEditAnnee.setDisplayFormat(_translate("main_window_biblioApp", "yyyy"))
        self.label_6.setText(_translate("main_window_biblioApp", "                Resume"))
        self.doubleSpinBoxPrix.setSuffix(_translate("main_window_biblioApp", "euro"))
        self.label_7.setText(_translate("main_window_biblioApp", "                      Prix"))
        self.pushButtonNouveau.setText(_translate("main_window_biblioApp", "Nouveau"))
        self.pushButtonSauvegarder.setText(_translate("main_window_biblioApp", "Sauvegarder"))
        self.pushButtonSupprimer.setText(_translate("main_window_biblioApp", "Supprimer"))
        self.menuFichier.setTitle(_translate("main_window_biblioApp", "Fichier"))
        self.actionQuitter.setText(_translate("main_window_biblioApp", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window_biblioApp = QtWidgets.QMainWindow()
    ui = Ui_main_window_biblioApp()
    ui.setupUi(main_window_biblioApp)
    main_window_biblioApp.show()
    sys.exit(app.exec_())

